### ISSUE TITLE
Support for customizing the toplevel module list of a package.

### ISSUE THREAD

**Issue by dbuenzli** [b0-system/odig#18]
Most likely under the form of an ocamldoc fragment installed by a package. That will be used instead of the processing done by #1.

**Comment by trefis** [comment]
I think @lpw25 wanted these kind of fragments to have the `.mld` extension (for "ml doc"). The idea being that at some point we also plan to support things like
```ocaml
(** Some comment blablabla
    {!inline external_doc_file.mld}
    And some more comments. *)
```
in odoc.

**Comment by dbuenzli** [comment]
For a pkg `PKG`. This fragment should be installed as `$DOCDIR/$PKG/odig-assets/index.mld`

**Comment by dbuenzli** [comment]
And @trefis suggests that if `$DOCDIR/$PKG/odoc-manual/index.ml` exists, that one should take over.

**Comment by dbuenzli** [comment]
Maybe we can even do it without `odig-assets` at all. That seems simpler.

**Comment by dbuenzli** [comment]
Implemented on master.

To be clear this only happens if a `$(DOCDIR)/$PKG/odoc-pages/index.mld` is installed and AFAIK `dune` based system do that automatically for their packages and `index.mld` files.

More details can be found in the [manual](https://b0-system.github.io/odig/doc/odig/packaging.html#odoc_api_and_manual).
