### ISSUE TITLE
Support for customizing the toplevel header of the package list

### ISSUE THREAD

**Issue by dbuenzli** [b0-system/odig#19]
Just so that doc sets published online, can avoid having e.g. the pointless `For /home/opam/.opam/4.03.0/lib.` that can be seen on http://docs.mirage.io. 

This should not be used to organize information though as it won't be available to local users of `odig`, #18 or module preambles should be used instead for this.

**Comment by avsm** [comment]
It would be nice to have this, so that I can customise the landing page of docs.mirage.io

**Comment by dbuenzli** [comment]
This is available on `master` via the `--index-intro` option which allows to specify an `mld` file to define the introduction before the package list. See [the manual](https://b0-system.github.io/odig/doc/odig/manual.html#publish) and `odig odoc --help`.

The scheme is not totally optimal yet (e.g. you have to redo a potential toc yourself) since the package list page itself is not generated via an mld file (we'd need https://github.com/ocaml/odoc/issues/94); only the intro is generated via `odoc html-fragment`. The advantage however is that you can choose what you put in the toc side bar on this page (here's [an example](https://github.com/b0-system/odig/blob/master/sample/intro.mld)). 

Also the `--index-title` option of `odig odoc` allows to set the page title of the package list page.
