### ISSUE TITLE
Option to exclude some cmis in dependency graph

### ISSUE THREAD

**Issue by Gbury** [b0-system/odig#40]
When trying to look at the cmi-deps of a given package, I find the output sometimes cluttered by all the deps on the stdlib modules. Would it make sense to add an option to `odig graph cmi-deps` to ignore/exlcude some packages in the dependency graph (particularly the stdlib ?).

**Comment by dbuenzli** [comment]
Do you actually find yourself using `odig graph` ? 

I was never convinced by `dot`'s abilities in rendering them and was planning to get rid of the sub command in the current `odig` rewrite that is going on in favour of the approach mentioned [here](https://github.com/dbuenzli/omod/issues/3). 

(The graph linked there was produced by massaging the output of `odig cobj -d --json cmi`).

**Comment by Gbury** [comment]
I don't use it much, no.
I was actually trying to replace a manual invocation to `ocamldoc -dot -dot-reduce *.ml *.mli` after switching a project from manual makefiles to a proper build system, and it happened to be harder than I thought. `odig graph` seemed to be a viable replacement, but it appears that the transitive reduction done by ocamldoc is key to having an actually readable graph (more than simply removing the stdlib modules from the graph).
For comparison, here are the two generated graphs:
- odig : https://gbury.eu/public/archi_odig.pdf (after removing external deps (i.e stdlib) using a custom script)
- ocamldoc: https://gbury.eu/public/archi.pdf (using some additional subgraphs/clusters automatically inserted with a small script)

**Comment by dbuenzli** [comment]
Thanks ! Interesting. 

What do you think about these kind of [interactive graphs](https://bl.ocks.org/dbuenzli/602b2de70b33224a4792764fbf77c2be) based on [this paper](https://aviz.fr/wiki/uploads/Teaching2014/bundles_infovis.pdf) ?

As far as I remember I generated those with: 
```
odig cobj -p --json -d cmi PKG1 PKG2 PKG3
```
See [this file](https://gist.github.com/dbuenzli/602b2de70b33224a4792764fbf77c2be#file-cmi-deps-json) in the gist.

**Comment by Gbury** [comment]
Sorry for the delay.

Finally we're going to use [ocamldot](https://github.com/facebook/infer/tree/master/dependencies/ocamldot) (not to be confused with the ocamldot released on opam..) as it seems to do exactly what ocamldoc was doing, but with a much more lightweight invocation (it simply processes the output of ocamldep).


The interactive graphs seem interesting, but I actually prefer the hierarchical layout of dot when it comes to have a graphical representation of the dependency chains between a few modules. I feel like the interactive graphs are a better fit when analyzing a large number of modules and you need some kind of overview of the dependencies, whereas the dot graphs give you a more detailed representation (which, of course, does not scale, ^^).

**Comment by dbuenzli** [comment]
@Gbury thanks for getting back to me with your thoughts and experience. 

In any case this won't happen in this project whose scope got narrowed to documentation matters only (and thus documentation build artefacts like `cmt`, `cmti` and `cmi` files only). Your comment is however food for thought [here](https://github.com/dbuenzli/omod/issues/3).
