### ISSUE TITLE
specify a CNAME file in gh-pages-amend

### ISSUE THREAD

**Issue by avsm** [b0-system/odig#45]
One thing I noticed while refreshing docs.mirage.io is that gh-pages-amend does not provide the option to also add a `CNAME` file in order to have a custom domain.  The manual git scripts there currently do:

```
echo docs.mirage.io > .gh-pages/CNAME
```

It looks like `B0_github` needs to have that plumbed through before it can be added to odig.

**Comment by dbuenzli** [comment]
> It looks like `B0_github` needs to have that plumbed through before it can be added to odig.

Not really. An option could be added to add an update [here](https://github.com/b0-system/odig/blob/master/src/gh_pages_amend.ml#L12) but yourself is suspect you can also simply start with a:

```
echo "docs.mirage.io" > CNAME
gh-pages-amend CNAME .gh-pages/CNAME
```
or even add it yourself manually.

**Comment by dbuenzli** [comment]
Just in case that is not clear unless you specify  `.` as the destination which replaces the whole root whatever you amend *adds* to what is in the `gh-pages` branch.

**Comment by dbuenzli** [comment]
@avsm Could you please point me to the GitHub documentation regarding that `.gh-pages/CNAME` file. All I can find is web ui based [procedures](https://help.github.com/en/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site).

**Comment by avsm** [comment]
It's all moved around but this https://help.github.com/en/articles/troubleshooting-custom-domains#github-repository-setup-errors has it as a 'tip'
