### ISSUE TITLE
some synopsis missing in the index page

### ISSUE THREAD

**Issue by avsm** [b0-system/odig#47]
Some packages in the index HTML page are missing a `synopsis` but do have a version, despite the synopsis being in the opam file. It's not clear what the pattern is fo the missing synopsis:

e.g. front page of https://docs.mirage.io or https://b0-system.github.io/odig/doc@odig.gruvbox.dark/index.html has the same issue.

**Comment by dbuenzli** [comment]
A package name that exhibits the behaviour would be nice.

**Comment by avsm** [comment]
That's what it is indeed; the ones with the synopsis missing are opam 1.2 format files. I'd be fooled because the docs.mirage.io has installed some older opam packages due to version constraints holding them back.  Looks like porting all to opam 2.0 format will eventually make this go away (an example package is asetmap).
