### ISSUE TITLE
Missing spaces in objects

### ISSUE THREAD

**Issue by Wilfred** [b0-system/odig#49]
E.g. on https://b0-system.github.io/odig/doc/visitors/VisitorsRuntime/index.html I see:

```ocaml
class 'selfmap : object ... end
```

This is missing the space between the  `'self` and `map`.

**Comment by dbuenzli** [comment]
Thanks for the report. 

Yes I noticed too yesterday and opened https://github.com/ocaml/odoc/issues/338

Generally issues you may be seeing with the markup *output* itself should be filed with the `odoc` tracker. If you see issues where an  `odig.*` stylesheet is at fault, you are at the right place.
