### ISSUE TITLE
Odig library is configured incorrectly

### ISSUE THREAD

**Issue by kwshi** [b0-system/odig#52]
When trying to load the odig library in OCaml, the following error occurs:
```
Cannot find file /.../.opam/default/lib/odig/odig.cma.
```

The folder `/.../.opam/default/lib/odig/` contains the following files:
- `META`
- `odig_odoc.*`
- `odig_odoc_page.*`
- `odig_support.*`
- `opam`

but no `odig.*` files.

When installed, the package has the following META file:

```
version = "0.0.4"
requires = "b0.std b0.b00 b0.care"
archive(byte) = "odig.cma"
archive(native) = "odig.cmxa"
plugin(byte) = "odig.cma"
plugin(native) = "odig.cmxs"
```

Evidently, this is incorrect, because something about the build configuration seems to indicate the existence of an `odig.*` set of files, when there is no such collection.

**Comment by dbuenzli** [comment]
Thanks for the report. That's wrong indeed the library is `odig_support`.
