### ISSUE TITLE
0-level comment cuts off rest of html

### ISSUE THREAD

**Issue by bluddy** [b0-system/odig#53]
I'm not sure how prevalent this is, but at least in `ldap`, the `mli` file has a 0-level comment mid-way. When generating the odoc for this package, everything after and including that comment is cut off from the final products, including sub-modules that aren't generated. `odig` waits for these artifacts to be produced and fails.

Steps to reproduce:
* Install `ldap` with opam.
* Run `odig odoc`

**Comment by dbuenzli** [comment]
What do you suggest as far as `odig` is concerned ?

**Comment by bluddy** [comment]
Sorry @dbuenzli I got confused. This belongs in odoc.

**Comment by dbuenzli** [comment]
No problem, I think `odoc` should simply turn that `0` into a `1` and warn.

**Comment by bluddy** [comment]
Agreed.
