### ISSUE TITLE
Is there a way to make odig proceed despite missing files?

### ISSUE THREAD

**Issue by bluddy** [b0-system/odig#56]
I'm trying to build the universe of packages, and inevitably there will be a few that have some kind of issue. Rather than chase them endlessly, I want the cache mechanism not to fail and to just give me a best effort output with what it has. Is this possible to do with odoc?

**Comment by dbuenzli** [comment]
That's already the way it works no ?

**Comment by dbuenzli** [comment]
In any case. If something doesn't work the way you want please first try with `master` (you'll need an `opam pin b0 --dev` for that) -- quite a few changes have been made (you may be interested by the new `odig log` btw.). 

Then precisely state your problem on a repo case example and what should be done in your opinion. Meanwhile I'm closing this.
