### ISSUE TITLE
Incorrect browser detection for local html on Linux Mint / Ubuntu

### ISSUE THREAD

**Issue by emengd** [b0-system/odig#60]
Hi, I'm not sure whether this bug is really with odig or not but I couldn't figure out how odig decides what tool to use looking through the source so I ask. Basically, my default browser is Firefox for both `http://`URL's and local HTML files. However odig will open local HTML (generated from `odig doc`) in Chrome. I find this surprising as both `open` and `xdg-open` correctly open the same files in Firefox. `odig browse` will also correctly open links in Firefox, and `odig doc --browser=firefox` also works correctly. Any idea what might be wrong?

I'm using Linux Mint 20 (based on Ubuntu 20.04), and odig 0.0.5 on OCaml 4.10.0. Feel free to ask for more information or experiments, of course.

**Comment by dbuenzli** [comment]
The code is [here](https://github.com/b0-system/b0/blob/master/src-b00/kit/b00_www_browser.mli). Normally things should work as documented under the `--browser` option. Do you have the  `BROWSER` variable defined by any chance ? 

It seems surprising that `odig doc` and `odig browse` give you different browser they use the same code.

**Comment by dbuenzli** [comment]
Also `open` should only end up being used on `Linux`, basically it's either `BROWSER` with a program that can be found in the `PATH` or a fallback to  `xdg-open`. The actual code is [here](https://github.com/b0-system/b0/blob/f1d40f4c8055bbb1415c4fca08bfb8cf3c242c95/src-b00/kit/b00_www_browser.ml#L70-L81).

**Comment by emengd** [comment]
Never mind I just realized I wasted your time. It turns out that I had been trying `xdg-open` on `.opam/default/var/cache/odig/html/index.html` whose mime type is `text/html` while `odig doc odig` opens `.opam/default/var/cache/odig/html/odig/index.html` whose mime type is `application/xhtml+xml`, and for whatever reason I had Chrome set as default for the latter kind of files, while for the first kind and for `http://` url's I had Firefox as default. So this was just `xdg-open`, nothing to do with `odig`.

That said possibly the fact that the second file is classified as it is is not desirable? It seems that on the OCaml end this can be changed by removing the `xmlns` payload from the `<html>` tag. Also, it might be a bug in `xdg-mime`: `file --mime-type` gives `text/html` whether `xmlns` is there or not.

**Comment by dbuenzli** [comment]
Ok no problem.

> It seems that on the OCaml end this can be changed by removing the `xmlns` payload from the `<html>` tag. Also, it might be a bug in `xdg-mime`: `file --mime-type` gives `text/html` whether `xmlns` is there or not.

You may have to open an issue on `odoc` for that. `odig` just runs `odoc`.

**Comment by emengd** [comment]
Ok, I mistakenly thought `odoc` was also developed by you. I'm going to open an issue there. Thanks!
