### ISSUE TITLE
Environnement variable of opam take priority on commandline and will break odig opam output parsing

### ISSUE THREAD

**Issue by jorisgio** [b0-system/odig#66]
I'm not sure it is worth fixing, but in case OPAMVERBOSE environnement variable is set, it will break odig parsing via opam show --quiet since environnement variable as priority over commandline (which makes sense i think).

**Comment by dbuenzli** [comment]
> environnement variable as priority over commandline (which makes sense i think).

No it doesn't. Environment variables are supposed to change default values, not override cli specifications (otherwise basically any form of shell scripting is doomed) I think you should report this in opam.
