### ISSUE TITLE
odig doesn't respect local opam switch

### ISSUE THREAD

**Issue by MisterDA** [b0-system/odig#67]
cmdliner.1.1.0 was just released. My default opam switch has cmdliner.1.0.4 because another package conflicts with cmdliner.1.1.0. I've created a local opam switch where cmdliner.1.1.0 is installed, however when I'm using that local switch `odig doc cmdliner`  shows the docs for cmdliner.1.0.4 installed in the global switch; odig should rather generate and show the docs for the local switch.

**Comment by dbuenzli** [comment]
Are you using the `odoc` from the local switch ?

**Comment by dbuenzli** [comment]
Also `odig conf` will tell you where it sources from. And `odig conf --help` will tell you how these things are determined.
