### ISSUE TITLE
Allow documentation to live in a separate directory than .opam

### ISSUE THREAD

**Issue by patrick-nicodemus** [b0-system/odig#74]
This issue proposes a fix for a problem that likely only affects a small group of users - it is not an odig problem, it is just a feature request for dealing with incompatibility with other software - so it is not necessarily worth the development time, but I thought I would document the problem. I'm sorry, I know this is not your problem, but if enough people will benefit from the fix it may be worth it.

The problem is as follows: Applications distributed in the Linux ["snap" application-packaging format](https://snapcraft.io/about) do not have permission to access hidden files on the user's machine, including files in .opam. This cannot be customized or changed by the user. Firefox is commonly distributed as a snap, perhaps some other browsers are as well. Therefore, I cannot open the odig documentation in Firefox on Ubuntu without copying it all to a non-hidden directory and manually opening it in the browser.

There are several fixes.
1. Remove Firefox and install it using a different software package that has different file permissions, or just install Chrome instead
2. Move the .opam switch to a folder which isn't hidden, i.e. 'opam' (the easiest way to do this is likely to reinstall OCaml, otherwise you risk many links to the .opam directory becoming broken)
3. Allow the user to configure odig so that documentation is stored in a non-hidden folder called opam-doc.

 I am not sure that the niche is large enough to justify the fix but I don't know of a good end user workaround. Last time I hit this problem, I just moved the root opam directory to a non-hidden directory, but it takes a while to reinstall everything. I will probably patch the problem this time by uninstalling Firefox and installing it in a different way.

**Comment by dbuenzli** [comment]
Isn't that just a matter of using `--cache-dir` or the `ODIG_CACHE_DIR` environment variable appropriately ?

**Comment by dbuenzli** [comment]
You may want to have a read to `odig conf --help`. Feel free to reopen if something is missing to achieve your goal.
